generation: 2023
model: full_kit
zuuu_version: 1.2
neck_orbita_zero:
    top: 0.0
    middle: 0.0
    bottom: 0.0
camera_parameters:
    left:
        fx: 0.0
        fy: 0.0
        cx: 0.0
        cy: 0.0
        k1: 0.0
        k2: 0.0
        k3: 0.0
        p1: 0.0
        p2: 0.0
    right:
        fx: 0.0
        fy: 0.0
        cx: 0.0
        cy: 0.0
        k1: 0.0
        k2: 0.0
        k3: 0.0
        p1: 0.0
        p2: 0.0
